spring:
  application:
    name: resthateoas
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:/data/hateoasdb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
#    database-platform: org.hibernate.dialect.H2Dialect
server:
  port: 8087

